### ISSUE TITLE
OBI protocol documentation not found

### ISSUE THREAD

**Issue by pcotret** [openhwgroup/programs#559]
## Bug Title
OBI protocol documentation may have disappeared.

### Type
Indicate whether the type of problem you found:
* I was looking at the CV32E40X documentation especially for the OBI protocol specs.
> OpenHW Open Bus Interface (OBI) protocol, version 1.5.0, https://github.com/openhwgroup/core-v-docs/blob/master/cores/obi/OBI-v1.5.0.pdf

I understand that `core-v-docs` may have been rename as this `programs` repository. However, I couldn't find the OBI protocol documentation (even if it's based on RST, I could regenerate the PDF by myself).

### Location of Issue
Please provide:
https://docs.openhwgroup.org/projects/cv32e40x-user-manual/en/latest/intro.html

### Additional context
We basically have the same issue with other cores, sometimes with older version of OBI specs.
For instance, the CV32E40P : https://docs.openhwgroup.org/projects/cv32e40p-user-manual/en/latest/intro.html

**Comment by pcotret** [comment]
EDIT: I found the documentation I was looking for in an older commit (https://github.com/openhwgroup/programs/tree/a8e6076c6cfecd57e584f66ce6414cc3b75bf0ca/cores/obi).
However, the issue is still here.

**Comment by MikeOpenHWGroup** [comment]
Whoops!   Thanks for reporting this @pcotret.  It seems the OBI spec did not survive the transition from the "core-v-docs" repo to "programs".  I will work with @DBees to resolve this.  There are two aspects to resolving the issue:
- [ ] Restore the OBI spec.
- [ ] Update all links to the new location.

**Comment by Silabs-ArjanB** [comment]
@MikeOpenHWGroup @DBees I would like to add that moving OBI documentation under 'programs' is not very logical. Nobody will search it there. Can we keep a core-v-docs as well and keep 'programs' only for 'programs' related stuff?

**Comment by abukharmeh** [comment]
Saw @davideschiavone  opened this repo https://github.com/openhwgroup/obi !

**Comment by pcotret** [comment]
Great, thanks for the notice @abukharmeh :wink:

**Comment by MikeOpenHWGroup** [comment]
Can this issue be closed now?

**Comment by pcotret** [comment]
Link has to be updated in each CPU documentation (for instance, https://docs.openhwgroup.org/projects/cv32e40x-user-manual/en/latest/intro.html). But I think it's correct for this `programs` repository.
